import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    mySidebar: [
        {
            type: 'doc',
            id: 'index',
            label: '팀 및 이 문서에 대해',
        },
        {
            type: 'category',
            label: '퀀트 프로젝트',
            link: {
                type: 'doc',
                id: 'projects/index'
            },
            items: [
                {
                    type: 'category',
                    label: '얽힘 라이브러리',
                    link: {
                        type: 'doc',
                        id: 'projects/entanglementlib/index'
                    },
                    items: [
                        'projects/entanglementlib/sensitive-data-container',
                        'projects/entanglementlib/entlib-native',
                        'projects/entanglementlib/secure-tls-server'
                    ],
                },
                {
                    type: 'category',
                    label: '블루 브릿지',
                    link: {
                        type: 'doc',
                        id: 'projects/blue-bridge/index'
                    },
                    items: [ ],
                }
            ],
        },
        {
            type: 'category',
            label: '퀀트 개발자',
            link: {
                type: 'doc',
                id: 'quant-team/index'
            },
            items: [
                'quant-team/factory-control',
                'quant-team/secure',
                'quant-team/garden'
            ],
        },
        {
            type: 'category',
            label: '양자정보과학',
            link: {
                type: 'doc',
                id: 'quantum-information/index'
            },
            items: [
                {
                    type: 'category',
                    label: '기본 개념',
                    link: {
                        type: 'doc',
                        id: 'quantum-information/basic/index'
                    },
                    items: [

                    ]
                }
            ],
        },
    ],
};

export default sidebars;
