import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    mySidebar: [
        {
            type: 'doc',
            id: 'index', // ID
            label: '소개', // 사이드바에 표시 이름
        },
        {
            type: 'category',
            label: '프로젝트', // 사이드바에 표시 카테고리
            link: {
                type: 'doc',
                id: 'projects/index'
            },
            items: [
                {
                    type: 'category',
                    label: '얽힘 라이브러리',
                    link: {
                        type: 'doc',
                        id: 'projects/entanglementlib/index'
                    },
                    items: [
                        'projects/entanglementlib/pqc-algorithms'
                    ],
                }
            ],
        },
        {
            type: 'category',
            label: '퀀트 개발자 기초',
            link: {
                type: 'doc',
                id: 'quant-team/index'
            },
            items: [
                'quant-team/factory-control',
                'quant-team/secure'
            ],
        },
        {
            type: 'category',
            label: '양자정보과학',
            link: {
                type: 'doc',
                id: 'quantum-information/index'
            },
            items: [
                // 'quantum-information/factory-control',
                // 'quantum-information/secure'
            ],
        },
    ],
};

export default sidebars;
